### PR TITLE
Specify the hostname

### PR DESCRIPTION
**Pull request by guidodobboletta**
This PR is mostly intended for people that want to run this server on VMs or devices such as a raspberry PI as apparently Intellij checks whether the license server is still valid every X amount of hours (I think it's around 3-4).

With this change, you could have the server listening all the time without the need to turn it on often.

### CODE REVIEW

**Comment by rodrigogs** [comment]
Nice, I was just thinking about making it possible hahahaha

**Comment by guidodobboletta** [comment]
One of the ideas I had is that instead of having a single activation server as default that it would try a list of default servers (4 or 5) until one works. 

That would be the default behaviour, if not the user could then specify a different server via options and it would only try to activate with that one.

**Comment by rodrigogs** [comment]
It would'nt work, because Intellij makes just one request. So it will fail at the first try, and the user will have to click `Activate` again.

**Comment by guidodobboletta** [comment]
Ah that is unfortunate! If you need any more help with some other contributions let me know since I really like this project 👍

**Pull request merged**
